# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Esat Can/Desktop/Work/My Softwares/With Python/ECG/Launch/Anasayfa - untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ana(object):
    def setupUi(self, Ana):
        Ana.setObjectName("Ana")
        Ana.resize(820, 600)
        Ana.setMinimumSize(QtCore.QSize(820, 600))
        Ana.setMaximumSize(QtCore.QSize(820, 600))
        self.centralwidget = QtWidgets.QWidget(Ana)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 310, 181, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chckEngine = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chckEngine.setFont(font)
        self.chckEngine.setObjectName("chckEngine")
        self.verticalLayout.addWidget(self.chckEngine)
        self.chckElectric = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chckElectric.setFont(font)
        self.chckElectric.setObjectName("chckElectric")
        self.verticalLayout.addWidget(self.chckElectric)
        self.chckFuel = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chckFuel.setFont(font)
        self.chckFuel.setObjectName("chckFuel")
        self.verticalLayout.addWidget(self.chckFuel)
        self.chckTires = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chckTires.setFont(font)
        self.chckTires.setObjectName("chckTires")
        self.verticalLayout.addWidget(self.chckTires)
        self.chckRadio = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.chckRadio.setFont(font)
        self.chckRadio.setObjectName("chckRadio")
        self.verticalLayout.addWidget(self.chckRadio)
        self.sliderPower = QtWidgets.QSlider(self.centralwidget)
        self.sliderPower.setGeometry(QtCore.QRect(700, 180, 71, 301))
        self.sliderPower.setMaximum(105)
        self.sliderPower.setOrientation(QtCore.Qt.Vertical)
        self.sliderPower.setObjectName("sliderPower")
        self.lblPower = QtWidgets.QLabel(self.centralwidget)
        self.lblPower.setGeometry(QtCore.QRect(690, 90, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblPower.setFont(font)
        self.lblPower.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPower.setObjectName("lblPower")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(650, 0, 161, 104))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblPow4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(24)
        self.lblPow4.setFont(font)
        self.lblPow4.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPow4.setObjectName("lblPow4")
        self.verticalLayout_2.addWidget(self.lblPow4)
        self.lblPow3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(18)
        self.lblPow3.setFont(font)
        self.lblPow3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPow3.setObjectName("lblPow3")
        self.verticalLayout_2.addWidget(self.lblPow3)
        self.lblPow2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(12)
        self.lblPow2.setFont(font)
        self.lblPow2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPow2.setObjectName("lblPow2")
        self.verticalLayout_2.addWidget(self.lblPow2)
        self.lblPow1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(6)
        self.lblPow1.setFont(font)
        self.lblPow1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPow1.setObjectName("lblPow1")
        self.verticalLayout_2.addWidget(self.lblPow1)
        self.lblPow = QtWidgets.QLabel(self.centralwidget)
        self.lblPow.setGeometry(QtCore.QRect(700, 500, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.lblPow.setFont(font)
        self.lblPow.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPow.setObjectName("lblPow")
        self.lblError = QtWidgets.QLabel(self.centralwidget)
        self.lblError.setGeometry(QtCore.QRect(10, 200, 171, 111))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblError.setFont(font)
        self.lblError.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lblError.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblError.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblError.setLineWidth(1)
        self.lblError.setMidLineWidth(0)
        self.lblError.setScaledContents(False)
        self.lblError.setAlignment(QtCore.Qt.AlignCenter)
        self.lblError.setObjectName("lblError")
        self.lblDroneImage = QtWidgets.QLabel(self.centralwidget)
        self.lblDroneImage.setGeometry(QtCore.QRect(230, 10, 371, 501))
        self.lblDroneImage.setText("")
        self.lblDroneImage.setPixmap(QtGui.QPixmap("drone.png"))
        self.lblDroneImage.setScaledContents(False)
        self.lblDroneImage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDroneImage.setObjectName("lblDroneImage")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 301, 161))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.btnExt = QtWidgets.QPushButton(self.centralwidget)
        self.btnExt.setGeometry(QtCore.QRect(30, 522, 81, 31))
        self.btnExt.setObjectName("btnExt")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(620, 510, 75, 31))
        self.btnStart.setObjectName("btnStart")
        Ana.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ana)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        Ana.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ana)
        self.statusbar.setObjectName("statusbar")
        Ana.setStatusBar(self.statusbar)

        self.retranslateUi(Ana)
        self.sliderPower.valueChanged['int'].connect(self.lblPow.setNum)
        QtCore.QMetaObject.connectSlotsByName(Ana)

    def retranslateUi(self, Ana):
        _translate = QtCore.QCoreApplication.translate
        Ana.setWindowTitle(_translate("Ana", "Anasayfa"))
        self.chckEngine.setText(_translate("Ana", "Engine Power"))
        self.chckElectric.setText(_translate("Ana", "Electrical Power"))
        self.chckFuel.setText(_translate("Ana", "Fuel Connect"))
        self.chckTires.setText(_translate("Ana", "Tire Lock"))
        self.chckRadio.setText(_translate("Ana", "Radio Conncet"))
        self.lblPower.setText(_translate("Ana", "Engine \n"
"Power"))
        self.lblPow4.setText(_translate("Ana", "-----------"))
        self.lblPow3.setText(_translate("Ana", "-----------"))
        self.lblPow2.setText(_translate("Ana", "-----------"))
        self.lblPow1.setText(_translate("Ana", "-----------"))
        self.lblPow.setText(_translate("Ana", "OFF"))
        self.lblError.setText(_translate("Ana", "ERROR WİNDOW"))
        self.label_3.setText(_translate("Ana", "BLACKNIGHT GROUND \n"
"CONTROL SYSTEMS"))
        self.btnExt.setText(_translate("Ana", "EXIT"))
        self.btnStart.setText(_translate("Ana", "START"))

